- grafana/PostgreSQLDetails.json
Changed Filesystem graph to show each mountpoint usage.
Removed Disk Free gauge
Added sparklines to all gauges
> Fix filesystem graphs in PostgreSQLDetails

- grafana/PostgreSQLDetails.json
Set height for FileSystem graph
Change colspan for last row gauges
> Cosmetic changes

- exporter/node/ccp_pg_isready10.sh
- exporter/node/ccp_pg_isready94.sh
- exporter/node/ccp_pg_isready95.sh
- exporter/node/ccp_pg_isready96.sh
- grafana/PostgreSQL.json
Main Dashboard now shows Primary in Green and Replica in Blue
> Added support to detect Primary and Replica

- grafana/crunchy_grafana_datasource.yml
> Fix access method

- exporter/postgres/pgbackrest-info.sh
- exporter/postgres/pgmonitor.conf
- grafana/Overview.json
- grafana/PGBackrest.json
Fix refresh in PGBackrest dashboard
> Add new Overview desktop for easy access

- grafana/Bloat_Details.json
- grafana/CRUD_Details.json
- grafana/ETCD_Details.json
- grafana/Filesystem_Details.json
- grafana/OS_Details.json
- grafana/OS_Overview.json
- grafana/Overview.json
- grafana/PGBackrest.json
- grafana/PG_Details.json
- grafana/TableSize_Details.json
- hugo/content/changelog/_index.md
- hugo/content/exporter/_index.md
- hugo/content/prometheus/_index.md
Made grafana dashboards titles, refresh times & links consistent.
Updated documentation. Added notes about upgrading to hugo changelog.
> Update documentation. Fix grafana dashboard consistency.

- hugo/content/exporter/_index.md
- hugo/content/grafana/_index.md
- hugo/content/prometheus/_index.md
The following will update some minor spacing and formatting issues when the markdowns are translated to pdf.
> Update Documentation Spacing

- hugo/content/changelog/_index.md
- hugo/content/exporter/_index.md
- hugo/content/grafana/_index.md
Updated release notes and fixed some language in other documentation to make it clearer
> Update release notes for 4.2. Update language in docs.

- prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.example
> Fix syntax error in PG prometheus rules file (#171)

- exporter/postgres/queries_common.yml
- prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.example
This is a simple PR to fix a spelling error.
> Fix spelling of "gauge"

- exporter/postgres/crunchy-postgres-exporter-pg10-el6.service
- exporter/postgres/crunchy-postgres-exporter-pg11-el6.service
- exporter/postgres/crunchy-postgres-exporter-pg12-el6.service
- exporter/postgres/crunchy-postgres-exporter-pg94-el6.service
- exporter/postgres/crunchy-postgres-exporter-pg95-el6.service
- exporter/postgres/crunchy-postgres-exporter-pg96-el6.service
- exporter/postgres/crunchy-postgres-exporter@.service
Fail service when files listed in QUERY_FILE_LIST are missing.
Fixes (issue) #162 
> Service file not detecting invalid files in QUERY_FILE_LIST

- hugo/content/changelog/_index.md
- hugo/content/exporter/_index.md
- hugo/content/prometheus/_index.md
Add documentation for the blackbox_exporter
> Add blackbox_exporter docs. Update changelog.

- grafana/containers/crud_details.json
- grafana/containers/pgbackrest.json
- grafana/containers/pod_details.json
- grafana/containers/postgresql_details.json
- grafana/containers/postgresql_overview.json
- grafana/containers/postgresql_service_health_overview.json
- grafana/containers/prometheus_alerts.json
- prometheus/crunchy-prometheus.yml.containers
* Remove the instance label from container scrapes
The regular expression did not work for clusters with a dash in their
name. The `pod` label works for individual instances while the
`pg_cluster` label captures the cluster name correctly.
Issue: [ch8765]
* Remove the service label from container scrapes
This label is deprecated and better represented by combining the
`pg_cluster` and `role` labels.
Also removed the defunct `ccp_query_count` metric from the Service
Health dashboard and removed an invalid link definition.
Issue: [ch8765]
* Define variables consistently for containers
Most dashboards have variables by the same name (cluster, pod, etc.) but
some dashboards define them differently which breaks links between those
dashboards. Now, `cluster` is always a single value, except on …
> Merge development for 4.4-RC3

- exporter/postgres/queries_nodemx.yml
- exporter/postgres/setup_pg10.sql
- exporter/postgres/setup_pg11.sql
- exporter/postgres/setup_pg12.sql
- exporter/postgres/setup_pg95.sql
- exporter/postgres/setup_pg96.sql
- grafana/containers/pgbackrest.json
- grafana/containers/pod_details.json
- grafana/containers/postgresql_details.json
- prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.containers.example
> Development to Main for v4.4-RC5

- exporter/postgres/queries_pg13.yml
- exporter/postgres/queries_pg_stat_statements_full_pg12.yml
- exporter/postgres/queries_pg_stat_statements_full_pg13.yml
- exporter/postgres/queries_pg_stat_statements_pg10.yml
- exporter/postgres/queries_pg_stat_statements_pg11.yml
- exporter/postgres/queries_pg_stat_statements_pg12.yml
- exporter/postgres/queries_pg_stat_statements_pg13.yml
- exporter/postgres/queries_pg_stat_statements_pg95.yml
- exporter/postgres/queries_pg_stat_statements_pg96.yml
- grafana/QueryStatistics.json
> Dev to Mainline for v4.4-RC7

- exporter/postgres/queries_pg96.yml
> Dev to Mainline for v4.4-RC8

- LICENSE
Update to correct years in the LICENSE file
> update LICENSE with correct date years

- exporter/postgres/setup_pg10.sql
- exporter/postgres/setup_pg11.sql
- exporter/postgres/setup_pg12.sql
- exporter/postgres/setup_pg13.sql
- exporter/postgres/setup_pg96.sql
- hugo/content/changelog/_index.md
> Fix search path

- hugo/content/changelog/_index.md
- postgres_exporter/common/pg14/queries_general.yml
- postgres_exporter/common/pg14/queries_pg_stat_statements.yml
- postgres_exporter/common/pg14/queries_pg_stat_statements_full.yml
- postgres_exporter/common/pg14/queries_pg_stat_statements_reset_info.yml
- postgres_exporter/common/pg14/setup.sql
- postgres_exporter/linux/pg14/sysconfig.postgres_exporter_pg14
- postgres_exporter/linux/pg14/sysconfig.postgres_exporter_pg14_per_db
> Add support for PostgreSQL 14

- postgres_exporter/common/queries_pgbouncer.yml
Fixes #  Issue 288 (https://github.com/CrunchyData/pgmonitor/issues/288)
Depends on #  
> fixed pgbouncer queries

- .commitlintrc.yml
- .github/CODEOWNERS
- .pre-commit-config.yaml
Update this repo for parity with paar (codeowners, triggers)
> feat: add pre-commit configs to the repo

- .commitlintrc.yml
- .github/CODEOWNERS
- .github/pull_request_template.md
- .pre-commit-config.yaml
- hugo/content/changelog/_index.md
- hugo/content/exporter/_index.md
- postgres_exporter/common/pg10/queries_general.yml
- postgres_exporter/common/pg11/queries_general.yml
- postgres_exporter/common/pg12/queries_general.yml
- postgres_exporter/common/pg13/queries_general.yml
- postgres_exporter/common/pg14/queries_general.yml
- postgres_exporter/common/queries_pgbouncer.yml
Update slot monitoring query to account for logical slots on replicas (patroni feature)
Update changelog and documentation for next release.
Update PR Template & CODEOWNERS
Get pgbouncer fix merged back into development branch. It had gotten merged into main
Fixes #290
Depends on #  
> Fix slot metric query to account for replica slots

- node_exporter/linux/sysconfig.node_exporter
Fixes for issues found in 4.8.0RC1
Update sysconfig for node_exporter 1.4
Fixes #  
Depends on #  
> Fixes for version 4.8.0RC1

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/293.yml
- changelogs/fragments/297.yml
- changelogs/fragments/305.md
- changelogs/fragments/307.yml
- changelogs/fragments/v4.8.0.md
- hugo/content/changelog/_index.md
Generated changelog for 4.8.0 and added to documentation
Fixes #  
Depends on #  
> Changelog for 4.8.0

- postgres_exporter/common/queries_global.yml
*Please fill this template out fully; failure to do so can result in rejection of your PR.*
Please describe the changes made by your PR. This description should be at a high-level but detailed enough that a reviewer understands the scope of the fix or enhancement and can easily judge the PRs validity at addressing the stated issue/feature. Please fully describe any new or changed feature and whether said change is user-facing or not:
The max_query_time was not filtering out sessions that were in 'idle in transaction'.  Adjusted query to exclude idle and idle in transaction sessions from max_query_time. …
> Fix max_query_time for ccp_connection_stats

- changelogs/fragments/334.yml
- changelogs/fragments/344.yml
- prometheus/common/alert-rules.d/crunchy-alert-rules-pg.yml.example
Update the name of the new primary detection rule for consistency
Add changelog fragments for recent PRs
closes #
If this PR depends on another PR or resolution of another issue, please indicate that here using a separate 'depends' line for each dependency.
depends on #
If you have an **external** dependency (packages, portal updates, etc), add the 'BLOCKED' tag to your PR.
If your code touches …
> fix: update new rule name. add changelog fragments

- build/packages.yml
- changelogs/fragments/355.yml
- hugo/content/exporter/_index.md
Update build file to include new setup file for postgres_exporter materialized views
If you have an **external** dependency (packages, portal updates, etc), add the 'BLOCKED' tag to your PR.
> chore: update build file for new postgres_exporter setup files

- changelogs/fragments/350.yml
- grafana/common/PG_Details.json
Relabel the cache hit ratio dial to label it as lifetime for better clarity
Use the new proposed formula for the cache hit ratio on the graph to better give instantaneous insight on the cache hit ratio status
closes #350 
If you have an **external** dependency (packages, portal updates, etc), add the 'BLOCKED' tag to your PR.
- [1] PostgreSQL, Specify version(s):  11
If your code touches Prometheus, …
> fix: adjust cache hit ratio labels and calculations on grafana dashboard

- grafana/containers/crunchy_grafana_dashboards.yml
- grafana/containers/crunchy_grafana_datasource.yml
- grafana/containers/pgbackrest.json
- grafana/containers/pod_details.json
- grafana/containers/postgresql_details.json
- grafana/containers/postgresql_overview.json
- grafana/containers/postgresql_service_health.json
- grafana/containers/prometheus_alerts.json
- grafana/containers/query_statistics.json
- prometheus/containers/crunchy-prometheus.yml.containers
Assorted changes to update containers related dashboards and configuration.
- Pull the query stats WAL panel into containers dashboards
- Update the `expr` in Grafana `query_statistics` dashboard panel for WAL
- Use `PROMETHEUS` data source name in dashboards
- Simplify the Prometheus config to remove unnecessary options 
- Remove redundant labels (previously merged in #300)
- Provide comments around relabel_configs
- Use a kube discovery selector for the alertmanager and exporter pods
- I have made …
> Updates for containers config

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/350.yml
- changelogs/fragments/366.yml
- hugo/content/changelog/_index.md
> Release v4.10.0
