CHANGELOG
exporter/README.md
prometheus/README.md
prometheus/crunchy-prometheus.yml

Added config option to prometheus so it stops storing the built-in metrics from postgres_exporter that we are not using.
Also updated the README's to include some instructions for non-package installs. Can work on splitting it out to different files once we start supporting other OS's besides RHEL/Centos.

Ignore exporter metrics. Non-package install instructions.

---

README.md

Was linking to un-maintained exporter fork in our repository. Just pointing it back at original upstream.

Fix link to postgres_exporter upstream

---

grafana/BloatDetails.json
grafana/CRUD_Details.json
grafana/OSResourceDetails.json
grafana/PostgreSQLDetails.json
grafana/TableSize_Detail.json

This pull request makes the following changes to make pgMonitor more compatible with the container suite:
• Moves total bloat graph to the BloatDetails dashboard.  In the container suite we cannot support bloat check at this time, thus making this graph broken.
• Moves memory, swap, filesystem, system load and cpu graphs to a new dashboard - ResourceDetails.  In the container suite the node-exporter cannot run in the same container as the PostgreSQL container, making these graphs inaccurate.  We can choose to not import this dashboard in containers to not confuse users.
• Optimizes the graphs for small displays by moving legends to the bottom of the graph instead of being on the right.

Optimize dashboards for containers

---

exporter/postgres/setup_pg10.sql
exporter/postgres/setup_pg11.sql
exporter/postgres/setup_pg94.sql
exporter/postgres/setup_pg95.sql
exporter/postgres/setup_pg96.sql

Adding a check to see if the `ccp_monitoring` user exists prior to running the `CREATE ROLE` command to make the SQL idempotent.

Add if not exist check for ccp_monitoring role

---

exporter/README.md

If we use some additional `useradd` options then we don't need to `mkdir` or `chown` by hand

use additional useradd options to skip doing things by hand

---

README.md
hugo/content/_index.md

Rather than showing image, goto crunchydata.com when click on crunchy logo in Sponsors sections.

Fix hyperlink

---

prometheus/alert-rules.d/crunchy-alert-rules-node.yml.example

Need to specify `ext[234]` instead of just `ext` in rules file checks.

Fix ext wildcard spec

---

grafana/PGBouncer.json

The dashboard uses [[pgnode]] for the server state count graph. This results in no data since the var should be [[pgnodes]] (plural).
See PR #139

Fixing pgnodes var name bug

---

CODEOWNERS

Github teams method didn't work as planned

Reverting CODEOWNERS back to individual team members

---

grafana/Bloat_Details.json
grafana/CRUD_Details.json
grafana/ETCD_Details.json
grafana/Filesystem_Details.json
grafana/OS_Details.json
grafana/OS_Details.json.win
grafana/OS_Overview.json
grafana/OS_Overview.json.win
grafana/Overview.json
grafana/PGBackrest.json
grafana/PGBouncer.json
grafana/PG_Details.json
grafana/PG_Overview.json
grafana/Prometheus_Alerts.json
grafana/TableSize_Details.json

Bring grafana dashboards up to date with changes as of 6.5. May mean a minimum requirement of 6.5 for pgmonitor 4.2, but intention was to make that the new minimum requirement anyway.

Re-exported playbooks from Grafana 6.5. No functionality changes.

---

prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.example

Typo in the `crunchy-alert-rules-pg.yml.example` file causes prometheus to fail starting when it's put in place as is. This was introduced in new changes to pgMonitor 4.2/HA 1.8
Tested with playbook(s):  `crunchy-ha-postgresql-3-node`

Fix syntax error in PG prometheus rules file

---

exporter/postgres/queries_bloat.yml
exporter/postgres/queries_common.yml
exporter/postgres/queries_pg94.yml
exporter/postgres/queries_pg95.yml
exporter/postgres/queries_pg96.yml
hugo/content/changelog/_index.md
hugo/content/exporter/_index.md

Add a list & description of metrics that we collect for PostgreSQL. 
The new `ccp_postmaster_runtime_start_time_seconds` metric that was added in 4.2 was a duplication of the existing `ccp_postmaster_uptime_seconds` metric. Use the new one and mark the old one for deprecation.
The `ccp_wal_activity_count` metric in the 9.4, 9.5 and 9.6 queries file was mislabeled as a "count". The 10+ query files have this properly named as `ccp_wal_activity_total_size_bytes`. Mark the old one for deprecation. 
Refer to upstream documentation for node & wmi metrics.
Fixes (issue) #157

Add metrics list. Fix duped and mislabeled metrics.

---

exporter/postgres/queries_common.yml.win
exporter/postgres/queries_per_db.yml.win

Add new query files that are for use in the Windows package. Windows cannot efficiently gather object size information on databases with many objects. This can cause the exporter to time out and stop all metric collection.

Add new query files for windows

---

exporter/postgres/queries_nodemx.yml
prometheus/crunchy-prometheus.yml.containers

The 'Crunchy Collect' container has been moved from the Crunchy Containers project to the Postgres
Operator project and renamed to 'Crunchy Postgres Exporter'. This PR updates the Prometheus config file used 
for container deployments to match the new container name.
Also, it updates the beginning and ending comments from referring to 'pod_metrics.yml' to 
the current name, 'queries_nodemx.yml'.

Container related updates to Prometheus Configs

---

prometheus/crunchy-prometheus.yml.containers

This change updates the `rule_files` section of the prometheus config to include all rules files in a given directory. This will allow container users to mount a directory of alerting rules files to the container and have each file pulled in. This also follows how the base [crunchy-prometheus.yml](https://github.com/CrunchyData/pgmonitor/blob/82a1e39f5126cc7a77ee3ad55654f51e59263c23/prometheus/crunchy-prometheus.yml#L70) is setup.

Update crunchy-prometheus.yml.containers to include all rules.yml dir

---

grafana/containers/crud_details.json
grafana/containers/pgbackrest.json
grafana/containers/pod_details.json
grafana/containers/postgresql_details.json
grafana/containers/postgresql_overview.json
grafana/containers/postgresql_service_health_overview.json
grafana/containers/prometheus_alerts.json
prometheus/crunchy-prometheus.yml.containers

These patches update the container scrapes and dashboards to better utilize the labels provided by Crunchy PostgreSQL Operator. Namely, the `pg_cluster` label is applied to all the instances that form a cluster and the Kubernetes Pod name suffices to identify an instance. The `service` and derived `instance` labels have been removed and replaced with the above.
Along the way, I updated the Grafana template variables to be consistently single- or multi-valued so that the current cluster and instance stay selected as one follows dashboard links.
Issue: [ch8765]
Tested with ~playbook(s)~:  Crunchy PostgreSQL Operator

Updates to container dashboards

---

exporter/postgres/queries_nodemx.yml
exporter/postgres/setup_pg10.sql
exporter/postgres/setup_pg11.sql
exporter/postgres/setup_pg12.sql
exporter/postgres/setup_pg95.sql
exporter/postgres/setup_pg96.sql

This PR has two updates. 
For the first, the fs_type usage value for ccp_nodemx_data_disk causes an error in the relevant logs:
"Could not parse string: strconv.ParseFloat: parsing \"xfs\": invalid syntax" source="postgres_exporter.go:739"
"Unexpected error parsing column:  ccp_nodemx_data_disk fs_type xfs\n" source="postgres_exporter.go:1361"
To correct this, the fs_type usage value has been updated to "LABEL" in place of "GAUGE".
For the second, per the pgnodemx documentation:
"PostgreSQL version 9.5 or newer is required. On PostgreSQL version 9.6 or earlier, a role called
pgmonitor must be created, and the user calling these functions must be granted that role."
As such, the 'pgmonitor' role has been added to the 'setup_pg95.sql' and 'setup_pg96.sql' exporter scripts.
Please note, no …

Postgres exporter configuration updates related to the pgnodemx extension

---

exporter/postgres/queries_nodemx.yml
grafana/containers/pod_details.json
prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.containers.example

This change addresses two integration issues with the PostgreSQL
Operator project:
An issue was discovered where monitor.proc_diskstats() is not
returning /pgdata when using NFS backed PVs. To correct this,
this update takes the original ccp_nodemx_data_disk query
used by the exporter and places it under a new heading,
ccp_nodemx_disk_activity. A new version of ccp_nodemx_data_disk
is then created that does not join monitor.proc_mountinfo() with
monitor.proc_diskstats(), allowing the /pgdata mount point to
be returned. These two queries no only return values when `mount_point`
is `/pgwal`, `/pgdata`, and `/tablespaces/%`.
The corresponding change to pod_details.json points the 'Disk
Activity' panel to the new 'ccp_nodemx_disk_activity' metric name.
This change also adds an example pg …

Updates for postgres-operator integration

---

grafana/containers/pgbackrest.json
grafana/containers/postgresql_details.json

Fixes some typos related to the pgBackRest dashboard for containers.
Tested with Crunchy PostgreSQL Operator on OpenShift.

Fix pgBackRest link and panel for containers

---

prometheus/alert-rules.d/crunchy-alert-rules-blackbox.yml.example
prometheus/alert-rules.d/crunchy-alert-rules-etcd.yml.example
prometheus/alert-rules.d/crunchy-alert-rules-node.yml.example
prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.containers.example
prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.example

This change gets rid of whitespace in the alerting rules files. The whitespace in the file was making the yml unreadable once mounted to a Kubernetes Configmap
```
groups:\n- name: alert-rules\n  rules:\n      \n##########
EXPORTER RULES ##########\n  - alert: PGExporterScrapeError\n    expr: pg_exporter_last_scrape_error
> 0\n    for: 60s\n    labels:\n      service: postgresql\n      severity: critical\n
\     severity_num: 300\n    annotations:\n      summary: 'Postgres Exporter running
...
```
Once whitespace is removed
```
groups:
- name: alert-rules
rules:
########## EXPORTER RULES ##########
- alert: PGExporterScrapeError
expr: pg_exporter_last_scrape_error > 0
for: 60s
...
```
**Tested …

Trim whitespace

---

exporter/postgres/queries_pg10.yml
exporter/postgres/queries_pg11.yml
exporter/postgres/queries_pg12.yml
exporter/postgres/queries_pg13.yml
exporter/postgres/queries_pg95.yml
exporter/postgres/queries_pg96.yml
hugo/content/changelog/_index.md
hugo/content/exporter/_index.md

Allow for monitoring the time for the longest running query that is blocked by a heavyweight lock

Add metric for monitoring for blocked queries

---

exporter/postgres/queries_pg96.yml

The backend_type column had not yet been added in PG 9.6 for the connection metrics. This was added when the blocked query time was added in an 4.4RC6.

Fix query for connection metrics in PG96

---

prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.example

The threshold values for the backup alerts are matched exactly to the given time period they're set to monitor (24hrs, 7 days). If the runtimes aren't exactly the same from day to day, this can lead to false alerts. Added a 12hr buffer time onto the alerts. As long as archiving is being monitored as well, a delay in alerting that a backup failed isn't a big deal.

Add buffer to backrest alert thresholds

---

prometheus/crunchy-alertmanager.yml

Current provided alertmanager config has options which will cause errors during initial setup if not fixed or commented out. Comment these out by default and provide a config that should "just work" in most situations if a local smtp provider is available.
Fixes (issue) #192 

Simplify alertmanager config to avoid errors on initial setup

---

prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.example

Include a default alert rule that can alert on any failover occurrence. 
Fixes (issue) #180 

Add automatic failover alert

---

prometheus/alert-rules.d/crunchy-alert-rules-pg.yml.example

Invalid spacing was causing promtool validation of alert rules for pg to fail. Introduced in PR #219 so not a bug in previous released versions.

Fix spacing to satisfy yml formatting

---

grafana/common/PGBackrest.json
grafana/common/PG_Details.json
postgres_exporter/common/pg10/setup.sql
postgres_exporter/common/pg11/setup.sql
postgres_exporter/common/pg12/setup.sql
postgres_exporter/common/pg13/setup.sql
postgres_exporter/common/pg96/setup.sql
postgres_exporter/linux/pgbackrest-info.sh

1. pgbackrest-info is not handling newline in stanza collection command.
2. BACKREST_STANZAS and BACKREST_CONFIGS uses space delimiter
3. Fix PGBackrest dashboard to remove unneeded dependency on jobname
4. Update setup.sql to pass system id to pgbackrest-info for filtgering

PGBacckrest and other fixes

---

prometheus/linux/alert-rules.d/crunchy-alert-rules-node.yml.example

Disable the disk fill prediction alert. It had been marked experimental and generally requires tuning to not cause false alerts.

Disable the disk fill predict alert by default

---

grafana/common/Bloat_Details.json
grafana/common/CRUD_Details.json
grafana/common/ETCD_Details.json
grafana/common/PGBackrest.json
grafana/common/PGBouncer.json
grafana/common/PG_Details.json
grafana/common/PG_Overview.json
grafana/common/Prometheus_Alerts.json
grafana/common/QueryStatistics.json
grafana/common/TableSize_Details.json
grafana/linux/Filesystem_Details.json
grafana/linux/Network_Details.json
grafana/linux/OS_Details.json
grafana/linux/OS_Overview.json
hugo/content/changelog/_index.md
postgres_exporter/common/queries_global.yml
prometheus/common/auto.d/ProductionDB.yml.example
prometheus/common/auto.d/ReplicaDB.yml.example
prometheus/linux/alert-rules.d/crunchy-alert-rules-node.yml.example
prometheus/linux/crunchy-prometheus.yml

Update dashboards to remove deprecated SingleStat panel and use new Stats panel. Use data links on Overview dashboards.
Incorporate changes from container dashboards.

Update Grafana dashboards for 7.4. Incorporate Container changes

---

alertmanager/common/crunchy-alertmanager.yml

This uses a template that was found in pgMonitor v4.4 and allows for containers users to begin configuration from this template.

Add template for bootstrapping Alertmanager for containers

---

grafana/common/PG_Overview.json
grafana/linux/OS_Overview.json
postgres_exporter/common/pg12/queries_pg_stat_statements_reset_info.yml
postgres_exporter/common/pg13/queries_pg_stat_statements_reset_info.yml

The overview dashboards are still not consistently showing the "current" value when set to a longer default timeframe. Set back to "5m" to ensure it's only looking at the last 5 minutes of data to keep the status more current.
Move the pg_stat_statements reset function to the pg12/13 folder since it is only supported in those versions.

Fixes since 4.5RC2 testing

---

postgres_exporter/common/queries_nodemx.yml

The queries that worked against memory.stat and cpu.stat were parsing
the virtual files once per metric rather than once. This causes the
queries to run about 50% slower than they should, and more importantly
means the collected metrics are not atomic snapshots of those values.
Fix that by rewriting the queries to perform the virtual file parsing
once followed by extracting the desired values.
Also add some missing important metrics. In particular,
memory.usage_in_bytes was not being collected.
Additionally grab clock timestamps in the same queries that collect the
cpu usage nanoseconds values. This ensures that the timestamps are
collected as close in time as possible to the cpu usage metrics, such
that some interesting calculations can be made to obtain cpu usage and
throttling …

Fix stat queries and add a few missing metrics

---

grafana/containers/pgbackrest.json
grafana/containers/pod_details.json
grafana/containers/postgresql_details.json
grafana/containers/postgresql_overview.json
grafana/containers/postgresql_service_health.json
grafana/containers/prometheus_alerts.json
grafana/containers/query_statistics.json
postgres_exporter/common/queries_nodemx.yml
prometheus/containers/crunchy-prometheus.yml.containers

1. Grafana dashboards for operator 5.0. Minimum grafana version 7.4.x
2. nodemx query fix for cpucfs_quota_us
3. Updated Prometheus config to reflect the label changes in operator 5.0

grafana and nodemx query changes for operator-5.0

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

Keep the .github folder consistent between paar and pgm

keep codeowners and templates in lockstep w/ paar

---

grafana/common/PG_Overview.json

Add missing pgcluster variable to url, this will open correct link in details dashboard.

PG Overview data link fix

---

postgres_exporter/common/queries_nodemx.yml

Adds a missing "when" to the `ccp_nodemx_cpucfs` query.

Fix ccp_nodemx_cpucfs Query

---

postgres_exporter/common/pg10/queries_general.yml
postgres_exporter/common/pg11/queries_general.yml
postgres_exporter/common/pg12/queries_general.yml
postgres_exporter/common/pg13/queries_general.yml
postgres_exporter/common/pg14/queries_general.yml
postgres_exporter/common/pg96/queries_general.yml
postgres_exporter/common/queries_global.yml

Change queries using now() to clock_timestamp(). If a query runs a little longer than expected, it could potentially result in negative values when doing math with time due to now() being the time at the beginning of the transaction vs a time value being returned when the query finally runs.
Fixes #237 

Change now() to clock_timestamp() in metric queries

---

prometheus/containers/alert-rules.d/crunchy-alert-rules-pg.yml.containers.example

1. DiskFillPredict alert was generating false alerts during ETL jobs especially on smaller-sized disks. So, I have added a disk usage condition to reduce the false alerts. This alert is very similar to the PGDiskUsage alert. But, works better regardless of the disk size. 
2. PGClusterRoleChange: This alert is to inform the users that there was a switchover/failover event on a particular PostgreSQL cluster. This is a generic alert that does not depend on a specific job or cluster like PGRecoveryStatusSwitch_Replica. So, users do not have to configure an alert for each cluster.
Fixes #  
Depends on #  
- [X ] Feature (change which adds functionality)  
Yes. Tested on openshift cluster 4.6

add disk usage condition to DiskFillPredict alert and PGClusterRoleChange alert

---

grafana/common/PG_Overview.json

Fix issue with Grafana 8+ not accepting decimal values that are not prepended with a zero as valid mapping values. Tested and adding the prepended zero works for Grafana 7.5 without any issues.
Fixes #265

Fix primary mapping value in pg overview dashboard for grafana 8+

---

grafana/common/ETCD_Details.json
grafana/common/crunchy_grafana_datasource.yml

Found another etcd dashboard with more details (https://grafana.com/grafana/dashboards/15308). Adapted it to our usage in Crunchy HA. Requires Grafana 8.3+
Added UID value to our prometheus datasource in Grafana. New dashboards in 8+ of grafana use this vs a name to determine which datasource they will use by default. Since we use provisioning this needs to be defined to avoid a random string generation.
Updated our dashboard file to remove deprecated values and simplify
Addresses the problem in Issue 281 by making sure to use the "instant" value where appropriate.
Fixes #281 
Depends on #  

New ETCD dashboard

---

grafana/linux/OS_Details.json

As reported, the left small panel in the OS Details for the file system list not consistent with the other panels. Fixes this as well as marking the dashboard as read-only. 
Fixes #286 

Fix Grafana filesystem panel consistency

---

postgres_exporter/linux/queries_backrest.yml
prometheus/common/alert-rules.d/crunchy-alert-rules-pg.yml.example

Add a metric to monitor for errors reported by pgBackRest (checksum errors, file truncation, invalid headers, etc). Added alert to monitor for changes in that metric (starts at line 380 in alert file)
This does not monitor for incomplete backup errors. That is already handled by the backrest timing metrics and alerts.
Added some clarification to what is a comment and what are actual alerts in the alert file (double hash for comments)
Tested by forcing corruption on a data file to cause a checksum error. While database was shut down, ran the following on a user table file (16659)
```
dd if=<(echo break things -n) of=16659 seek=1000 bs=12
```
Fixes #275 
- I have made …

Monitor for errors reported by pgBackRest

---

changelogs/README.md
changelogs/config.yaml

run `antsibull-changelog init --is-other-project` in repo to prep for using changelog fragments

prep repo for changelog fragments

---

prometheus/containers/crunchy-prometheus.yml.containers

The prometheus scrape_configs included some relabeling actions that seemed like no-ops -- renaming labels to themselves. This PR removes them, but also may be an opportunity to discuss why they were there in case I'm missing something.
I've tested this manually by checking certain metrics with those labels before / after removing them from the scrape configs.

Remove redundant labels from prometheus scrape

---

postgres_exporter/common/queries_nodemx.yml

As cgroup v2 support/adoption within Kubernetes continues to progress, users are encountering issues with broken pgnodemx exporter queries. This commit updates the paths where needed and returns 0 values for statistics that are no longer available.
Fixes #  
Version 2 of cgroup changes the names and locations for some of its statistics. For other v1 statistics, there is no exact v2 counterpart, such as memory.stat.rss, memory.stat.mapped_file, memory.kmem.usage_in_bytes.
References:
- [Exporter Queries Incompatible with 'Unified' Cgroup Mode #273](https://github.com/CrunchyData/pgmonitor/issues/273)
- [cgroup v1](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v1/)
- [cgroup v2](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html)
- [Enabling cgroup v2 on …

pgnodemx Exporter Queries For cgroups v2 Issue: [sc-15818]

---

changelogs/fragments/293.md
prometheus/linux/sysconfig.prometheus

Update the sysconfig file for Prometheus to use non-deprecated value for tsdb storage. Change to clearer `7d` value for retention. Reviewed other options in use by default for prometheus and alertmanager sysconfig and all look fine so far.
Fixes #293 

Update deprecated storage path variable in prometheus sysconfig

---

changelogs/fragments/120.yml
prometheus/linux/alert-rules.d/crunchy-alert-rules-node.yml.example

Allow node_exporter alerting for load to be based on CPU count. Allows lowering of default threshold and more accurate alerting.
closes #120 

Load by cpu count

---

pgbadger/run_pgbadger.py
postgres_exporter/common/queries_global.yml
postgres_exporter/common/queries_per_db.yml
postgres_exporter/windows/queries_common.yml

Query can be very slow, so remove the pg_namespace join. The original can be slow for pathologically bloated schemas with thousands of relations.
Change query from using a join on pg_namespace to using a cast to regnamespace instead. Requires Postgres 9.5 or later.
- [* ] Enhancement
closes #325

Improve system catalog query

---

changelogs/fragments/330.yml
prometheus/common/alert-rules.d/crunchy-alert-rules-pg.yml.example

Enable the data checksum alert by default for PG12 and above.
closes #330 

feat: enable datachecksum alert by default supported versions

---

prometheus/common/alert-rules.d/crunchy-alert-rules-pg.yml.example

*Please fill this template out fully; failure to do so can result in rejection of your PR.*
Please describe the changes made by your PR. This description should be at a high-level but detailed enough that a reviewer understands the scope of the fix or enhancement and can easily judge the PRs validity at addressing the stated issue/feature. Please fully describe any new or changed feature and whether said change is user-facing or not:
Add alert for cases where a Postgres HA cluster does not have an instance that is the leader/primary.
closes #
If this PR depends on another PR or resolution of another …

added alert rule for no primary

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/120.yml
changelogs/fragments/283.yml
changelogs/fragments/327.yml
changelogs/fragments/330.yml
changelogs/fragments/333.yml
changelogs/fragments/334.yml
changelogs/fragments/338.yml
changelogs/fragments/341.yml
changelogs/fragments/344.yml
changelogs/fragments/351.yml
changelogs/fragments/355.yml

Release notes generated by antsibull-changelog.
Had some formatting issues with some of the files that needed to be fixed as well
```
fragments/120.yml:0:0: invalid section: minor_change                                                
fragments/283.yml:0:0: invalid section: minor_change                                                
fragments/341.yml:0:0: invalid section: minor_change                                                                                                                                                     
```
Removed redundant entry about Grafana having minimal version of 8.5

feat: release notes for 4.9.0

---

changelogs/fragments/366.yml
hugo/content/_index.md
postgres_exporter/common/pg16/queries_general.yml
postgres_exporter/common/pg16/queries_pg_stat_statements.yml
postgres_exporter/common/pg16/queries_pg_stat_statements_reset_info.yml
postgres_exporter/common/pg16/setup.sql
postgres_exporter/linux/pg16/sysconfig.postgres_exporter_pg16
postgres_exporter/linux/pg16/sysconfig.postgres_exporter_pg16_per_db

Add PostgreSQL 16 support
closes #366

Pg16 Support

---

changelogs/fragments/250.yml
changelogs/fragments/template.yml.example
grafana/common/Prometheus_Alerts.json
grafana/common/crunchy_grafana_datasource.yml
hugo/content/grafana/_index.md

Add support for the new Alertmanager API interface in Grafana. Automatically provisions a new alertmanager and associates that with the Prometheus datasource.
Ran into an issue with the association not working in 9.5 when testing there, but it works in 9.2 :confused: 
https://community.grafana.com/t/prometheus-alertmanager-association-missing-in-9-5/102703
closes #250 
If this PR depends on another PR or resolution of another issue, please indicate that here using a separate 'depends' line for each dependency.
depends on #
If you have an **external** dependency (packages, portal updates, etc), add the …

feat: add support for new alertmanager interfaces in grafana

---

changelogs/fragments/371.yml
postgres_exporter/linux/pgbackrest-info.sh

https://github.com/CrunchyData/pgmonitor/issues/371
ccp_backrest_* metrics not collecting when log level is set to debug with the following errors:
```
Sep 22 22:38:34 u4-vpdb-ha2-01.sonic.com postgres_exporter[94461]: ts=2023-09-22T22:38:34.755Z caller=namespace.go:236 level=info err="Error running query on database \"\": ccp_backrest_last_diff_backup pq: end-of-copy marker corrupt"
Sep 22 22:38:35 u4-vpdb-ha2-01.sonic.com postgres_exporter[94461]: ts=2023-09-22T22:38:35.188Z caller=namespace.go:236 level=info err="Error running query on database \"\": ccp_backrest_last_full_backup pq: end-of-copy marker corrupt"
```
*Please fill this template out fully; failure to do so can result in rejection of your PR.*
Please describe the changes made by your PR. This description should be at a …

updating pgbackrest-info.sh to set the log-level to warn
